### ISSUE TITLE
Unable to set custom options when using validator

### ISSUE THREAD

**Issue by charles-jan** [emailable/emailable-ruby#11]
I want to pass some custom options when using validator, like "message". But I noticed that the validator didn't pass the options field into errors at the end.
Can I submit a pull request to support it?

**Comment by jclusso** [comment]
Is the purpose to be able to configure your own error message? If so, you can already do this by override the translations for any of the keys listed at https://github.com/emailable/emailable-ruby/blob/master/config/locales/en.yml.

**Comment by charles-jan** [comment]
> Is the purpose to be able to configure your own error message? If so, you can already do this by overriding the translations for any of the keys listed at https://github.com/emailable/emailable-ruby/blob/master/config/locales/en.yml.

You're right. But in addition, there are still some unresolved problems:
- The attribute value for recording the email address is not passed in error and therefore cannot be used in format, like: `%{value} is undeliverable`. （Of course, there are other ways to achieve the same effect, but they will be more complicated）
- We have some custom error handler are resolve error by custom options, but it can't be passed in now

**Comment by jclusso** [comment]
> I want return same message for all errors, but now I can only configure all error keys to the same value

We actually do this and the way we do it looks like this. 

```yaml
en:
  errors:
    messages:
      undeliverable: is undeliverable
      unknown: :errors.messages.undeliverable
```

> We have some custom error handler are resolve error by custom options, but it can't be passed in now

Not sure what you mean by this. Can you elaborate?

**Comment by charles-jan** [comment]
> Not sure what you mean by this. Can you elaborate?

Ok, for example, I pass an option with error in these ways:
```ruby
errors.add(:email, :invalid_email, reportable: true)
```
or
```ruby
validates :email,
        uniqueness: true,
        email: {states: %i[deliverable], reportable: true}
```

Then I can handle errors on validation like this：
```ruby
rescue_from ActiveRecord::RecordInvalid do |e|
    messages = e.record.errors.where(:email, reportable: true).map(&:message)
    ReportMailer.with(messages: messages).invalid_report_email.deliver_now
 end
```
This will only send me validation error messages that are configured to `reportable` as `true`

**Comment by jclusso** [comment]
Is this a standard supported thing with all validations in Rails? Can you link to some documentation for this? Happy to expand our validation to match options that are typically supported.

**Comment by charles-jan** [comment]
This may not be a standard, but the common validators in `active_model/validations` all support this. I guess this is to support the `error` option. I will submit a PR later.
