### ISSUE TITLE
Gem is missing requires

### ISSUE THREAD

**Issue by burlesona** [emailable/emailable-ruby#3]
If you just load a console and do `require 'emailable'`, it's missing a few requires before it will work, specifically just testing `Emailable.verify(...)` I found that I needed to require `uri`, `net/http`, and `json`. All very logical things, but since plain Ruby environments (outside Rails) won't autoload those, the gem needs to have them as explicit requires.

**Comment by eberquist** [comment]
@burlesona Can you confirm that the `require 'uri'` is necessary? After opening an irb console things seem to work with only needing `net/http` and `json`.

**Comment by burlesona** [comment]
I would guess that net/http itself requires URI, so if you do it in that order then URI is already loaded. When I tried calling Emailable.verify without requiring anything else it failed three times, first because URI was missing, then Net, then JSON.

**Comment by jclusso** [comment]
@burlesona this has been fixed in [3.1.1](https://github.com/emailable/emailable-ruby/releases/tag/3.1.1). This was unnoticed because our tests had net/http and JSON being required by other dependencies.
