### ISSUE TITLE
Some exceptions in the gem are not handled correctly

### ISSUE THREAD

**Issue by burlesona** [emailable/emailable-ruby#5]
I've had several issues where something goes wrong, but whatever went wrong is obscured by incorrect error handling inside the gem. The issue always looks like this:

```
.../lib/emailable.rb:54:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
```

If we trace that back it's this code:

```ruby
  class Error < StandardError
    attr_accessor :code, :message

    def initialize(code: nil, message: nil)
      @code = code
      @message = message
    end
  end
```

It's not orthodox Ruby to use keyword arguments for initializing an exception, and the error message indicates that some place in the code is likely doing something like:

```ruby
raise Error, 'My message.'
```

That would work if the definition of an Emailable::Error was changed as shown below - except that you can't pass a code that way.

```ruby
  class Error < StandardError
    attr_accessor :code

    def initialize(message = nil, code: nil)
      super(message)
      @code = code
    end
  end
```

Note that StandardError already has a message attribute and expects it to be the only argument, since you're inheriting you can just forward this along.

It looks like the main place this comes from is https://github.com/emailable/emailable-ruby/blob/master/lib/emailable/client.rb#L51. I think this call might need the error map to be splatted: `raise error_map[status.to_s].new(**error_attributes)`, but I'm not sure.

In any case, it would be better to follow the language convention for how errors work, then adjust the error map code. It could actually be a lot simpler:

1. `error_map` should really be a constant, not defined in the method, because it's unnecessary to build this data structure over again on every method call when it never changes.
2. Hash keys can be integers, so the status doesn't need to be treated as a string.
3. With the above changes there's really no need for an `error_attributes` hash.

Combined those changes would look like this:

```ruby
module Emailable
  class Client
    ERRORS = {
      400 => BadRequestError,
      401 => UnauthorizedError,
      402 => PaymentRequiredError,
      403 => ForbiddenError,
      404 => NotFoundError,
      429 => TooManyRequestsError,
      500 => InternalServerError,
      503 => ServiceUnavailableError,
    }.freeze

    # ...

    def request(method, endpoint, params = {})
      # ...

      status = response.status
      return response if status.between?(200, 299)
      raise ERRORS[status].new(response.body['message'], code: status)
    end
```

**Comment by jclusso** [comment]
@burlesona thanks for this. We've taken your suggestions and they are reflected in [3.1.1](https://github.com/emailable/emailable-ruby/releases/tag/3.1.1).
