### ISSUE TITLE
Batch.complete typo?

### ISSUE THREAD

**Issue by awei82** [emailable/emailable-ruby#6]
`batch.complete?` and `batch.status.complete?` are returning opposite values. I'm assuming this is not supposed to be the case?

https://github.com/emailable/emailable-ruby/blob/57b9746506089ed68c9dd25e2c4edcf89c8d0176/lib/emailable/batch.rb#L42-L44

**Comment by danarnold** [comment]
Thanks for bringing this to our attention. This has been fixed in [3.2.0](https://github.com/emailable/emailable-ruby/releases/tag/3.2.0).
